name: Reusable Workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
    # secret:
    # 	some-secret:
    # 		required: true
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{inputs.artifact-name}}
      - name: Output Information
        run: echo "Deploying and Uploading ..."
